# EJERCICIOS REPASO

## 02 Programación y herramientas avanzadas

##### 1. Crea un programa que genere una matriz de vectores aleatorios de tamaño ( 5 \times 3 ) (5 vectores en un espacio de 3 dimensiones) y luego calcule el producto punto entre un vector específico y todos los demás vectores de la matriz.

In [1]:
import numpy as np

# Generar una matriz de vectores aleatorios (5 vectores de 3 dimensiones)
matriz_vectores = np.random.rand(5, 3)

# Imprimir la matriz de vectores
print("Matriz de vectores:")
print(matriz_vectores)

# Escoger el primer vector
vector_referencia = matriz_vectores[0]

# Calcular el producto punto entre el vector de referencia y todos los demás
productos_punto = []
for i in range(matriz_vectores.shape[0]):
    if i != 0:  # Evitar calcular el producto punto con el mismo vector
        producto = np.dot(vector_referencia, matriz_vectores[i])
        productos_punto.append(producto)

# Imprimir los productos punto
print("\nProductos punto entre el vector de referencia y los demás vectores:")
for i, p in enumerate(productos_punto):
    print(f"Producto punto con el vector {i + 1}: {p:.4f}")

Matriz de vectores:
[[0.9052844  0.30807139 0.8913656 ]
 [0.56235747 0.62080189 0.97364254]
 [0.40258975 0.29992846 0.40018279]
 [0.22464702 0.48985411 0.11745309]
 [0.67611073 0.44758686 0.31442129]]

Productos punto entre el vector de referencia y los demás vectores:
Producto punto con el vector 1: 1.5682
Producto punto con el vector 2: 0.8136
Producto punto con el vector 3: 0.4590
Producto punto con el vector 4: 1.0302


##### 2. Crea un programa que realice las siguientes operaciones con un DataFrame que contenga información sobre un grupo de estudiantes. Las columnas del DataFrame incluirán: Nombre, Edad, Nota de Matemáticas, Nota de Historia, y Nota de Ciencias.

Las operaciones a realizar son:

1. Crear un DataFrame con datos ficticios de al menos 5 estudiantes.
2. Calcular y agregar una nueva columna al DataFrame que contenga la Nota Media de cada estudiante.
3. Filtrar el DataFrame para mostrar solo los estudiantes que tengan una media superior a 75.
4. Imprimir el DataFrame original y el DataFrame filtrado.

In [2]:
import pandas as pd

# Crear un diccionario con datos de estudiantes
data = {
    'Nombre': ['Ana', 'Juan', 'Luis', 'María', 'Pedro'],
    'Edad': [18, 19, 20, 21, 22],
    'Nota de Matemáticas': [80, 65, 90, 70, 85],
    'Nota de Historia': [75, 85, 70, 80, 90],
    'Nota de Ciencias': [90, 75, 60, 80, 88]
}

# Crear el DataFrame
df = pd.DataFrame(data)

# Calcular la Nota Media y agregar una nueva columna
df['Nota Media'] = df[['Nota de Matemáticas', 'Nota de Historia', 'Nota de Ciencias']].mean(axis=1)

# Filtrar el DataFrame para estudiantes con Nota Media superior a 75
df_filtrado = df[df['Nota Media'] > 75]

# Imprimir el DataFrame original
print("DataFrame original:")
print(df)

# Imprimir el DataFrame filtrado
print("\nDataFrame filtrado (Nota Media > 75):")
print(df_filtrado)

DataFrame original:
  Nombre  Edad  Nota de Matemáticas  Nota de Historia  Nota de Ciencias  \
0    Ana    18                   80                75                90   
1   Juan    19                   65                85                75   
2   Luis    20                   90                70                60   
3  María    21                   70                80                80   
4  Pedro    22                   85                90                88   

   Nota Media  
0   81.666667  
1   75.000000  
2   73.333333  
3   76.666667  
4   87.666667  

DataFrame filtrado (Nota Media > 75):
  Nombre  Edad  Nota de Matemáticas  Nota de Historia  Nota de Ciencias  \
0    Ana    18                   80                75                90   
3  María    21                   70                80                80   
4  Pedro    22                   85                90                88   

   Nota Media  
0   81.666667  
3   76.666667  
4   87.666667  
